#!/usr/bin/env bash

set -o noglob
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

ARGUMENTS=$@

container_name=${CONTAINER_NAME:-"temporal-index"}

command -v docker >/dev/null 2>&1 || { echo >&2 "Please install docker. E.g., go to https://www.docker.com/products/docker-desktop "; exit 1; }

docker info >/dev/null 2>&1 || { echo >&2 "Docker server is not running? "; exit 1; }

docker image inspect $container_name >/dev/null 2>&1 || ( echo "instantiating the container" ; docker build --no-cache -t $container_name -f $SCRIPTPATH/Dockerfile .  )

HOSTNAME=$(hostname)

docker run --rm \
  -e "HOST_HOSTNAME=${HOSTNAME}" \
  -v $(pwd):$(pwd):Z  \
  -w $(pwd)  \
  $container_name temporal-index $ARGUMENTS 



